[project]
name = "q3cibc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium-robotics>=1.4.2",
    "matplotlib>=3.10.8",
    "minari[all]>=0.5.3",
    "numpy>=2.4.1",
    "torch>=2.9.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
